language: node_js
node_js:
  - node
install:
  - npm install
script:
  # check grammar
  - npm run eslint
  - npm run stylelint
  # check if files in `dist/` is up-to-date
  - mv dist dist-tmp
  - npm run build
  - diff dist/bzoj.user.js dist-tmp/bzoj.user.js
  - diff dist/luogu.user.js dist-tmp/luogu.user.js
  - diff dist/luogu-custom.user.js dist-tmp/luogu-custom.user.js
  - rm -r dist-tmp
