language: node_js
node_js:
  - node
install:
  - yarn install
script:
  # check grammar
  - yarn eslint
  - yarn stylelint
  # check if files in `dist/` is up-to-date
  - mv dist _dist && yarn build && diff dist _dist
