language: node_js
node_js:
  - node
install:
  - npm install
script:
  # check grammar
  - npm run eslint
  - npm run stylelint
  # check if files in `dist/` is up-to-date
  - mv dist dist-tmp
  - npm run build
  - diff dist dist-tmp
