name: Scripts for BZOJ
namespace: https://www.lydsy.com/
version: 0.2.7
match:
  - https://lydsy.com/JudgeOnline/*
  - https://www.lydsy.com/JudgeOnline/*
run-at: document-start
updateURL: https://raw.githubusercontent.com/sxyz-edu/user-scripts/master/dist/bzoj.user.js
downloadURL: https://raw.githubusercontent.com/sxyz-edu/user-scripts/master/dist/bzoj.user.js
supportURL: https://github.com/sxyz-edu/user-scripts
