name: Scripts for BZOJ
namespace: https://www.lydsy.com/
version: 0.1.2
match:
  - https://www.lydsy.com/JudgeOnline/problem.php?id=*
  - https://www.lydsy.com/JudgeOnline/show.php?id=*
updateURL: https://raw.githubusercontent.com/sxyz-edu/user-scripts/master/dist/bzoj.user.js
downloadURL: https://raw.githubusercontent.com/sxyz-edu/user-scripts/master/dist/bzoj.user.js
supportURL: https://github.com/sxyz-edu/user-scripts
